### ISSUE TITLE
Cannot access files

### ISSUE THREAD

**Issue by kristasinga** [TrainingByPackt/Data-Science-for-Marketing-Analytics#1]
Hi

I can't open the files in this lesson. For example, the excel file says that the format/extension is not valid. Please advise. I just bought the book. Thank you.

K

**Comment by TommyBlanchard** [comment]
Can you be a bit more specific about what you're trying to do that isn't working? Is there a specific notebook that is giving you an error?

**Comment by kristasinga** [comment]
Hi!

I just figured it out. My apologies, I'm a new python & github user. Thank
you!
